## Data

In [6]:
import pandas as pd
import numpy as np

In [7]:
car = pd.read_csv("quikr_car.csv")

In [8]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [9]:
car.shape

(892, 6)

In [10]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [11]:
car["year"].unique()

<StringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [12]:
car["Price"].unique()

<StringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000',      '1,75,000',      '1,90,000',      '8,30,000',
      '2,50,000',      '1,82,000',
 ...
        '42,000',      '1,89,000',      '1,62,000',        '35,999',
     '29,00,000',        '39,999',        '50,500',      '5,10,000',
      '8,60,000',      '5,00,001']
Length: 274, dtype: str

In [13]:
car["company"].unique()

<StringArray>
[   'Hyundai',   'Mahindra',     'Maruti',       'Ford',      'Skoda',
       'Audi',     'Toyota',    'Renault',      'Honda',     'Datsun',
 'Mitsubishi',       'Tata', 'Volkswagen',          'I',  'Chevrolet',
       'Mini',        'BMW',     'Nissan',  'Hindustan',       'Fiat',
 'Commercial',     'MARUTI',      'Force',   'Mercedes',       'Land',
     'Yamaha',    'selling',     'URJENT',      'Swift',       'Used',
     'Jaguar',       'Jeep',       'tata',       'Sale',       'very',
      'Volvo',          'i',       '2012',       'Well',        'all',
          '7',          '9',    'scratch',     'urgent',       'sell',
       'TATA',        'Any',       'Tara']
Length: 48, dtype: str

In [14]:
car["kms_driven"].unique()

<StringArray>
[  '45,000 kms',       '40 kms',   '22,000 kms',   '28,000 kms',
   '36,000 kms',   '59,000 kms',   '41,000 kms',   '25,000 kms',
   '24,530 kms',   '60,000 kms',
 ...
   '60,123 kms',   '38,900 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 259, dtype: str

In [15]:
car["kms_driven"].describe()

count            840
unique           258
top       45,000 kms
freq              30
Name: kms_driven, dtype: object

In [16]:
car["fuel_type"].unique()

<StringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [17]:
car["name"].unique()

<StringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
             'Maruti Suzuki Alto 800 Vxi',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
 ...
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
  'Maruti Suzuki Alto 800 Select Variant',
             'Maruti Suzuki Ritz VXI ABS',
                       'tata zest 2017 f',
              'Tata Indica V2 DLE BS III',
                                     'Ta',
                    'Tata Zest XM Diesel',
               'Honda Amaze 1.2 E i VTEC',
              'Chevrolet Sail 1.2 LT ABS']
Length: 525, dtype: str

### quality
- year there are many non-year values
- year object to int
- price has ask for price , object to int
- company there are many int value
- kms_driven	object to int and Petrol and nan
- fuel_type nan value and keep 3 words of name
- there are 92 duplicated rows
- price has a wrong value 8500003
- kms_driven has impossible values like 40 and 0 for old cars and 400000

## Cleaning

In [18]:
backup=car.copy()

In [19]:
car=car[car["year"].str.isnumeric()].copy()
car["year"]=car["year"].astype(int)

In [20]:
car.info()

<class 'pandas.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    str
 1   company     842 non-null    str
 2   year        842 non-null    int64
 3   Price       842 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: int64(1), str(5)
memory usage: 46.0 KB

In [21]:
car['kms_driven'] = car['kms_driven'].astype('string')

car['kms_driven'] = car['kms_driven'].str.replace(',', '', regex=False)
car['kms_driven'] = car['kms_driven'].str.replace(
    r'\s*kms\s*', '', regex=True
)

car['kms_driven'] = pd.to_numeric(
    car['kms_driven'], errors='coerce'
)

print(car['kms_driven'].dtype)
print(car['kms_driven'].isna().sum())

Int64
4

In [22]:
car=car[car["Price"]!="Ask For Price"]

In [23]:
car["Price"] = (
    car["Price"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace(" ", "", regex=False)
)

In [24]:
car["Price"] = pd.to_numeric(car["Price"], errors="coerce")

In [25]:
car.info()

<class 'pandas.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    str
 1   company     819 non-null    str
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  817 non-null    Int64
 5   fuel_type   816 non-null    str
dtypes: Int64(1), int64(2), str(3)
memory usage: 45.6 KB

In [26]:
car=car[~car['fuel_type'].isna()]

In [27]:
car['fuel_type'].unique()

<StringArray>
['Petrol', 'Diesel', 'LPG']
Length: 3, dtype: str

In [28]:
car=car.dropna()

In [29]:
car=car.drop_duplicates()

In [30]:
car=car[car['Price']<6e6]
car=car[car['kms_driven']<=250000]
car=car[~((car['kms_driven']<1000)&(car['year']<=2016))]

In [31]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')
car['kms_driven']=car['kms_driven'].astype(int)

In [32]:
car=car.reset_index(drop=True)

In [33]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 716 entries, 0 to 715
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        716 non-null    object
 1   company     716 non-null    str
 2   year        716 non-null    int64
 3   Price       716 non-null    int64
 4   kms_driven  716 non-null    int64
 5   fuel_type   716 non-null    str
dtypes: int64(3), object(1), str(2)
memory usage: 33.7+ KB

In [34]:
car.describe()

              year         Price     kms_driven
count   716.000000  7.160000e+02     716.000000
mean   2012.358939  3.921933e+05   46691.790503
std       4.116953  3.755986e+05   31875.431512
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.650000e+05   28000.000000
50%    2013.000000  2.900000e+05   42000.000000
75%    2015.000000  4.899990e+05   59000.000000
max    2019.000000  3.100000e+06  200000.000000

In [35]:
print(car['fuel_type'].value_counts(dropna=False))

fuel_type
Petrol    387
Diesel    327
LPG         2
Name: count, dtype: int64

In [36]:
car.to_csv('cleaned_quikr_car.csv', index=False)

## Model

In [39]:
x=car.drop(columns=['Price'])
y= car['Price']

In [41]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
x, y, test_size=0.2, random_state=42
)

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder, FunctionTransformer
from sklearn.compose import make_column_transformer, TransformedTargetRegressor
from sklearn.pipeline import make_pipeline

In [43]:
column_trans = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'),
     ['name', 'company', 'fuel_type']),
    (FunctionTransformer(np.log1p), ['kms_driven']),
    remainder='passthrough'
)

In [44]:
lr=LinearRegression()

In [45]:
pipe=make_pipeline(column_trans,lr)
pipe=TransformedTargetRegressor(regressor=pipe,func=np.log,inverse_func=np.exp)

In [46]:
pipe.fit(x_train, y_train)

y_pred = pipe.predict(x_test)

In [47]:
r2_score(y_test,y_pred)

0.5572545765828172

In [48]:
from sklearn.model_selection import cross_val_score, RepeatedKFold

cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=42)
cross_val_score(pipe, x, y, cv=cv, scoring='r2').mean()

np.float64(0.6361881313655942)

In [49]:
pipe.fit(x,y)

TransformedTargetRegressor(func=<ufunc 'log'>, inverse_func=<ufunc 'exp'>,
                           regressor=Pipeline(steps=[('columntransformer',
                                                      ColumnTransformer(remainder='passthrough',
                                                                        transformers=[('onehotencoder',
                                                                                       OneHotEncoder(handle_unknown='ignore'),
                                                                                       ['name',
                                                                                        'company',
                                                                                        'fuel_type']),
                                                                                      ('functiontransformer',
                                                                                       FunctionTransformer(func=<ufunc 'log1p'>),
                                                                                       ['kms_driven'])])),
                                                     ('linearregression',
                                                      LinearRegression())]))

In [50]:
import pickle

In [51]:
pickle.dump(pipe, open('LinearRegression.pkl', 'wb'))

In [52]:
new_car = pd.DataFrame(
    [['Maruti Suzuki Swift', 'Maruti', 2019, 100, 'Petrol']],
    columns=['name', 'company', 'year', 'kms_driven', 'fuel_type']
)

pipe.predict(new_car)

array([624046.33231799])